In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
!pip install librosa noisereduce pydub tensorflow

Requirement already satisfied: librosa in /usr/local/lib/python3.12/dist-packages (0.11.0)
Collecting noisereduce
  Downloading noisereduce-3.0.3-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: pydub in /usr/local/lib/python3.12/dist-packages (0.25.1)
Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.20.0)
Requirement already satisfied: audioread>=2.1.9 in /usr/local/lib/python3.12/dist-packages (from librosa) (3.1.0)
Requirement already satisfied: numba>=0.51.0 in /usr/local/lib/python3.12/dist-packages (from librosa) (0.60.0)
Requirement already satisfied: numpy>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from librosa) (2.0.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from librosa) (1.16.3)
Requirement already satisfied: scikit-learn>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from librosa) (1.6.1)
Requirement already satisfied: joblib>=1.0 in /usr/local/lib/python3.12/dist-packages (from librosa) (1.5.3)
Requirement already satisfied: decorator>=4.3.0 in /usr/local/lib/python3.12/dist-packages (from librosa) (4.4.2)
Requirement already satisfied: soundfile>=0.12.1 in /usr/local/lib/python3.12/dist-packages (from librosa) (0.13.1)
Requirement already satisfied: pooch>=1.1 in /usr/local/lib/python3.12/dist-packages (from librosa) (1.9.0)
Requirement already satisfied: soxr>=0.3.2 in /usr/local/lib/python3.12/dist-packages (from librosa) (1.0.0)
Requirement already satisfied: typing_extensions>=4.1.1 in /usr/local/lib/python3.12/dist-packages (from librosa) (4.15.0)
Requirement already satisfied: lazy_loader>=0.1 in /usr/local/lib/python3.12/dist-packages (from librosa) (0.5)
Requirement already satisfied: msgpack>=1.0 in /usr/local/lib/python3.12/dist-packages (from librosa) (1.1.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from noisereduce) (3.10.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from noisereduce) (4.67.3)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (26.1)
Requirement already satisfied: protobuf>=5.28.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.1.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.80.0)
Requirement already satisfied: tensorboard~=2.20.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.20.0)
Requirement already satisfied: keras>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.13.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.16.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.47.0)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (0.19.0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba>=0.51.0->librosa) (0.43.0)
Requirement already satisfied: platformdirs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from pooch>=1.1->librosa) (4.9.6)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.4.22)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=1.1.0->librosa) (3.6.0)
Requirement already satisfied: cffi>=1.0 in /usr/local/lib/python3.12/dist-packages (from soundfile>=0.12.1->librosa) (2.0.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.10.2)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (11.3.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.1.8)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->noisereduce) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->noisereduce) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->noisereduce) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->noisereduce) (1.5.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->noisereduce) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib->noisereduce) (2.9.0.post0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.0->soundfile>=0.12.1->librosa) (3.0)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.10.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.10.0->tensorflow) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow) (0.1.2)
Downloading noisereduce-3.0.3-py3-none-any.whl (22 kB)
Installing collected packages: noisereduce
Successfully installed noisereduce-3.0.3

In [ ]:
!pip install tensorflow

Requirement already satisfied: tensorflow in /usr/local/lib/python3.12/dist-packages (2.20.0)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from tensorflow) (26.1)
Requirement already satisfied: protobuf>=5.28.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (5.29.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.1.2)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (1.80.0)
Requirement already satisfied: tensorboard~=2.20.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.20.0)
Requirement already satisfied: keras>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.13.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (2.0.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (3.16.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.12/dist-packages (from tensorflow) (0.5.4)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from astunparse>=1.6.0->tensorflow) (0.47.0)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras>=3.10.0->tensorflow) (0.19.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.13)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.4.22)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.10.2)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (11.3.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.1.8)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.12/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.10.0->tensorflow) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras>=3.10.0->tensorflow) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow) (0.1.2)

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.20.0

In [ ]:
import os
import numpy as np
import pandas as pd
import librosa
import noisereduce as nr

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [ ]:
respiratory_path = "/content/drive/MyDrive/AICA_Health_Project/datasets/respiratory_sound_database/Respiratory_Sound_Database/audio_and_txt_files"

lung_path = "/content/drive/MyDrive/AICA_Health_Project/datasets/Audio Files"

cremad_path = "/content/drive/MyDrive/AICA_Health_Project/datasets/AudioWAV"

In [ ]:
print(os.listdir(respiratory_path)[:5])

print(os.listdir(lung_path)[:5])

print(os.listdir(cremad_path)[:5])

['160_1b3_Tc_mc_AKGC417L.wav', '160_1b3_Al_mc_AKGC417L.wav', '160_1b3_Pr_mc_AKGC417L.txt', '160_1b3_Lr_mc_AKGC417L.wav', '160_1b4_Al_mc_AKGC417L.wav']
['BP103_N,N,P R U,81,F.wav', 'BP109_N,N,P L M,26,M.wav', 'BP105_Lung Fibrosis,Crep,A U R,44,M.wav', 'BP108_COPD,E W,P R L ,63,M.wav', 'BP104_Asthma,E W,P L U,45,F.wav']
['1080_DFA_DIS_XX.wav', '1079_TIE_SAD_XX.wav', '1079_TIE_NEU_XX.wav', '1079_TSI_NEU_XX.wav', '1079_TIE_FEA_XX.wav']

In [ ]:
def extract_features(file_path):

    try:
        audio, sr = librosa.load(file_path, sr=None)

        # Skip empty audio
        if len(audio) == 0:
            return None

        # Avoid divide by zero
        max_value = np.max(np.abs(audio))

        if max_value == 0:
            return None

        # Normalize
        audio = audio / max_value

        # Silence Removal
        trimmed_audio, _ = librosa.effects.trim(audio)

        # Skip if audio becomes empty
        if len(trimmed_audio) < 2048:
            return None

        # MFCC Extraction
        mfcc = librosa.feature.mfcc(
            y=trimmed_audio,
            sr=sr,
            n_mfcc=40
        )

        mfcc_mean = mfcc.mean(axis=1)

        return mfcc_mean

    except Exception as e:
        print("Error:", file_path)

        return None

In [ ]:
# Process Respiratory Dataset
features = []
labels = []

for file in os.listdir(respiratory_path):

    if file.endswith(".wav"):

        file_path = os.path.join(respiratory_path, file)

        feature = extract_features(file_path)

        if feature is not None:

            features.append(feature)

            labels.append("respiratory")

In [ ]:
#Process Lung Dataset
for file in os.listdir(lung_path):

    if file.endswith(".wav"):

        file_path = os.path.join(lung_path, file)

        feature = extract_features(file_path)

        if feature is not None:

            features.append(feature)

            labels.append("lung")

In [ ]:
# Process CREMAD Dataset
for file in os.listdir(cremad_path):

    if file.endswith(".wav"):

        file_path = os.path.join(cremad_path, file)

        feature = extract_features(file_path)

        if feature is not None:

            features.append(feature)

            labels.append("emotion")

In [ ]:
#Create Final Dataset
df = pd.DataFrame(
    features,
    columns=[f"MFCC_{i}" for i in range(40)]
)

df["label"] = labels

df

          MFCC_0      MFCC_1     MFCC_2  ...   MFCC_38   MFCC_39        label
0    -314.533295  138.169693  67.244629  ...  2.653219  1.918069  respiratory
1    -378.353699  102.738274  64.840103  ...  1.170348  1.160116  respiratory
2    -377.652252   84.995285  71.308640  ...  0.579796  0.541791  respiratory
3    -373.978699   96.170074  65.512604  ...  1.269495  0.917983  respiratory
4    -374.564392   93.873856  66.821350  ...  1.002638  1.107330  respiratory
...          ...         ...        ...  ...       ...       ...          ...
8692 -164.891373  107.691383  45.994995  ... -0.529202  2.381469      emotion
8693 -186.020615  112.033356  35.789379  ...  0.935070  2.147069      emotion
8694 -112.231071   99.433533  55.713417  ... -1.117260  0.085571      emotion
8695 -147.592392   85.866722  47.205723  ... -2.822653 -0.201877      emotion
8696 -190.853363  103.732231  44.356686  ... -0.367190 -0.682636      emotion

[8697 rows x 41 columns]

In [ ]:
df.shape

(8697, 41)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8697 entries, 0 to 8696
Data columns (total 41 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   MFCC_0   8697 non-null   float32
 1   MFCC_1   8697 non-null   float32
 2   MFCC_2   8697 non-null   float32
 3   MFCC_3   8697 non-null   float32
 4   MFCC_4   8697 non-null   float32
 5   MFCC_5   8697 non-null   float32
 6   MFCC_6   8697 non-null   float32
 7   MFCC_7   8697 non-null   float32
 8   MFCC_8   8697 non-null   float32
 9   MFCC_9   8697 non-null   float32
 10  MFCC_10  8697 non-null   float32
 11  MFCC_11  8697 non-null   float32
 12  MFCC_12  8697 non-null   float32
 13  MFCC_13  8697 non-null   float32
 14  MFCC_14  8697 non-null   float32
 15  MFCC_15  8697 non-null   float32
 16  MFCC_16  8697 non-null   float32
 17  MFCC_17  8697 non-null   float32
 18  MFCC_18  8697 non-null   float32
 19  MFCC_19  8697 non-null   float32
 20  MFCC_20  8697 non-null   float32
 21  MFCC_21  8697 non-null   float32
 22  MFCC_22  8697 non-null   float32
 23  MFCC_23  8697 non-null   float32
 24  MFCC_24  8697 non-null   float32
 25  MFCC_25  8697 non-null   float32
 26  MFCC_26  8697 non-null   float32
 27  MFCC_27  8697 non-null   float32
 28  MFCC_28  8697 non-null   float32
 29  MFCC_29  8697 non-null   float32
 30  MFCC_30  8697 non-null   float32
 31  MFCC_31  8697 non-null   float32
 32  MFCC_32  8697 non-null   float32
 33  MFCC_33  8697 non-null   float32
 34  MFCC_34  8697 non-null   float32
 35  MFCC_35  8697 non-null   float32
 36  MFCC_36  8697 non-null   float32
 37  MFCC_37  8697 non-null   float32
 38  MFCC_38  8697 non-null   float32
 39  MFCC_39  8697 non-null   float32
 40  label    8697 non-null   object
dtypes: float32(40), object(1)
memory usage: 1.4+ MB

In [ ]:
# Label Encoding
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

y = encoder.fit_transform(df["label"])

X = df.drop("label", axis=1)

In [ ]:
y

array([2, 2, 2, ..., 0, 0, 0])

In [ ]:
X

          MFCC_0      MFCC_1     MFCC_2  ...   MFCC_37   MFCC_38   MFCC_39
0    -314.533295  138.169693  67.244629  ...  3.122508  2.653219  1.918069
1    -378.353699  102.738274  64.840103  ...  1.086238  1.170348  1.160116
2    -377.652252   84.995285  71.308640  ...  0.674184  0.579796  0.541791
3    -373.978699   96.170074  65.512604  ...  1.407350  1.269495  0.917983
4    -374.564392   93.873856  66.821350  ...  0.759080  1.002638  1.107330
...          ...         ...        ...  ...       ...       ...       ...
8692 -164.891373  107.691383  45.994995  ... -2.664740 -0.529202  2.381469
8693 -186.020615  112.033356  35.789379  ...  0.189302  0.935070  2.147069
8694 -112.231071   99.433533  55.713417  ... -2.222892 -1.117260  0.085571
8695 -147.592392   85.866722  47.205723  ... -0.927283 -2.822653 -0.201877
8696 -190.853363  103.732231  44.356686  ... -1.149839 -0.367190 -0.682636

[8697 rows x 40 columns]

In [ ]:
print(encoder.classes_)

['emotion' 'lung' 'respiratory']

In [ ]:
# Train Test Split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [ ]:
# Build Deep Learning Model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

model = Sequential([
    Dense(128, activation='relu', input_shape=(40,)),
    Dense(64, activation='relu'),
    Dense(3, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
history = model.fit(
    X_train,
    y_train,
    epochs=50,
    batch_size=32,
    validation_split=0.2
)

Epoch 1/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9989 - loss: 0.0032 - val_accuracy: 0.9971 - val_loss: 0.0096
Epoch 2/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9993 - loss: 0.0022 - val_accuracy: 0.9978 - val_loss: 0.0116
Epoch 3/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9991 - loss: 0.0026 - val_accuracy: 0.9978 - val_loss: 0.0095
Epoch 4/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9991 - loss: 0.0018 - val_accuracy: 0.9978 - val_loss: 0.0141
Epoch 5/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9989 - loss: 0.0023 - val_accuracy: 0.9978 - val_loss: 0.0099
Epoch 6/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9991 - loss: 0.0038 - val_accuracy: 0.9964 - val_loss: 0.0085
Epoch 7/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9991 - loss: 0.0025 - val_accuracy: 0.9978 - val_loss: 0.0101
Epoch 8/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9993 - loss: 0.0017 - val_accuracy: 0.9964 - val_loss: 0.0085
Epoch 9/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9989 - loss: 0.0022 - val_accuracy: 0.9978 - val_loss: 0.0083
Epoch 10/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9984 - loss: 0.0051 - val_accuracy: 0.9964 - val_loss: 0.0071
Epoch 11/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9980 - loss: 0.0037 - val_accuracy: 0.9978 - val_loss: 0.0096
Epoch 12/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9996 - loss: 0.0013 - val_accuracy: 0.9971 - val_loss: 0.0114
Epoch 13/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9995 - loss: 0.0014 - val_accuracy: 0.9964 - val_loss: 0.0120
Epoch 14/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9993 - loss: 0.0029 - val_accuracy: 0.9978 - val_loss: 0.0135
Epoch 15/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9987 - loss: 0.0035 - val_accuracy: 0.9978 - val_loss: 0.0141
Epoch 16/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9987 - loss: 0.0031 - val_accuracy: 0.9964 - val_loss: 0.0188
Epoch 17/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9989 - loss: 0.0028 - val_accuracy: 0.9978 - val_loss: 0.0093
Epoch 18/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9977 - loss: 0.0058 - val_accuracy: 0.9964 - val_loss: 0.0092
Epoch 19/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9995 - loss: 0.0016 - val_accuracy: 0.9971 - val_loss: 0.0172
Epoch 20/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9995 - loss: 0.0016 - val_accuracy: 0.9971 - val_loss: 0.0142
Epoch 21/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9991 - loss: 0.0024 - val_accuracy: 0.9971 - val_loss: 0.0108
Epoch 22/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9980 - loss: 0.0043 - val_accuracy: 0.9978 - val_loss: 0.0132
Epoch 23/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9991 - loss: 0.0019 - val_accuracy: 0.9978 - val_loss: 0.0140
Epoch 24/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - accuracy: 0.9995 - loss: 9.4961e-04 - val_accuracy: 0.9964 - val_loss: 0.0172
Epoch 25/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9977 - loss: 0.0047 - val_accuracy: 0.9964 - val_loss: 0.0118
Epoch 26/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9991 - loss: 0.0030 - val_accuracy: 0.9986 - val_loss: 0.0084
Epoch 27/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9984 - loss: 0.0035 - val_accuracy: 0.9964 - val_loss: 0.0096
Epoch 28/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9984 - loss: 0.0030 - val_accuracy: 0.9971 - val_loss: 0.0119
Epoch 29/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.9989 - loss: 0.0031 - val_accuracy: 0.9971 - val_loss: 0.0120
Epoch 30/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9995 - loss: 0.0019 - val_accuracy: 0.9978 - val_loss: 0.0128
Epoch 31/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9993 - loss: 0.0015 - val_accuracy: 0.9978 - val_loss: 0.0145
Epoch 32/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9993 - loss: 0.0016 - val_accuracy: 0.9964 - val_loss: 0.0126
Epoch 33/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9989 - loss: 0.0026 - val_accuracy: 0.9978 - val_loss: 0.0111
Epoch 34/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9995 - loss: 0.0030 - val_accuracy: 0.9950 - val_loss: 0.0214
Epoch 35/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9989 - loss: 0.0032 - val_accuracy: 0.9978 - val_loss: 0.0149
Epoch 36/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9993 - loss: 0.0016 - val_accuracy: 0.9978 - val_loss: 0.0107
Epoch 37/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9995 - loss: 0.0016 - val_accuracy: 0.9978 - val_loss: 0.0136
Epoch 38/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9995 - loss: 0.0021 - val_accuracy: 0.9978 - val_loss: 0.0166
Epoch 39/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9995 - loss: 8.7041e-04 - val_accuracy: 0.9971 - val_loss: 0.0163
Epoch 40/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9993 - loss: 0.0013 - val_accuracy: 0.9978 - val_loss: 0.0176
Epoch 41/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9996 - loss: 0.0016 - val_accuracy: 0.9950 - val_loss: 0.0183
Epoch 42/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9966 - loss: 0.0179 - val_accuracy: 0.9964 - val_loss: 0.0280
Epoch 43/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9973 - loss: 0.0081 - val_accuracy: 0.9964 - val_loss: 0.0162
Epoch 44/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - accuracy: 0.9996 - loss: 0.0014 - val_accuracy: 0.9971 - val_loss: 0.0175
Epoch 45/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9987 - loss: 0.0022 - val_accuracy: 0.9971 - val_loss: 0.0163
Epoch 46/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9991 - loss: 0.0014 - val_accuracy: 0.9964 - val_loss: 0.0143
Epoch 47/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9987 - loss: 0.0018 - val_accuracy: 0.9971 - val_loss: 0.0130
Epoch 48/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9998 - loss: 9.9783e-04 - val_accuracy: 0.9971 - val_loss: 0.0155
Epoch 49/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9995 - loss: 0.0011 - val_accuracy: 0.9971 - val_loss: 0.0141
Epoch 50/50
174/174 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9989 - loss: 0.0019 - val_accuracy: 0.9971 - val_loss: 0.0161

In [ ]:
loss, accuracy = model.evaluate(X_test, y_test)

print("Accuracy:", accuracy)

55/55 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9960 - loss: 0.0279
Accuracy: 0.995976984500885